export const AiryTheme = {
  id: 'airy',
  name: 'Airy',
  desc: 'Sky Blue · Clean · Arcs',
  swatches: ['#ffffff', '#4a7fc4', '#f0f5ff'],
  timelineDecoration: false,
  sectionBadge: false,
  defaultGraphic: 'arcs',
  vars: {
    '--th-font-family': "'Inter', -apple-system, sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#4a7fc4',
    '--th-accent2': '#4a7fc4',
    '--th-page-bg': '#f6f9ff',
    '--th-chip-bg': '#dce8f8',
    '--th-chip-color': '#2a5fa8',
    '--th-chip-border': 'none',
    '--th-chip-radius': '4px',
    '--th-sec-rule-w': '0',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '12px',
    '--th-arc-color-1': 'rgba(180,210,238,0.45)',
    '--th-arc-color-2': 'rgba(180,210,238,0.30)',
  },
  typo: {
    headerBg:    { color: '#f6f9ff' },
    sidebarBg:   { color: '#c5daf0' },
    accentColor: { color: '#4a7fc4' },
    name:        { size: 34, bold: true,  italic: false, align: 'left', color: '#1a1a2e' },
    title:       { size: 13, bold: false, italic: false, align: 'left', color: '#4a7fc4' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#555555' },
    sectionTitle:{ size: 10.5, bold: true, italic: false, align: 'left', color: '#aaaaaa' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#1a1a2e' },
    jobCompany:  { size: 12, bold: false, italic: false, align: 'left', color: '#4a7fc4' },
    jobPeriod:   { size: 11, bold: false, italic: false, align: 'left', color: '#999999' },
    eduDegree:   { size: 13.5, bold: true, italic: false, align: 'left', color: '#1a1a2e' },
    eduInst:     { size: 12, bold: false, italic: false, align: 'left', color: '#4a7fc4' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a2e' },
  },
};
