export const BoldTheme = {
  id: 'bold',
  name: 'Bold',
  desc: 'Blue · Strong · Montserrat',
  swatches: ['#ffffff', '#2c5f9e', '#ffffff'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  vars: {
    '--th-font-family': "'Montserrat', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#2c5f9e',
    '--th-accent2': '#2c5f9e',
    '--th-page-bg': '#ffffff',
    '--th-chip-bg': 'transparent',
    '--th-chip-color': '#2c5f9e',
    '--th-chip-border': '1.5px solid #2c5f9e',
    '--th-chip-radius': '2px',
    '--th-sec-rule-w': '2px',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '14px',
  },
  typo: {
    headerBg:    { color: '#ffffff' },
    sidebarBg:   { color: '#1a2d4a' },
    accentColor: { color: '#2c5f9e' },
    name:        { size: 40, bold: true,  italic: false, align: 'left', color: '#111111' },
    title:       { size: 15, bold: true,  italic: false, align: 'left', color: '#2c5f9e' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#444444' },
    sectionTitle:{ size: 13, bold: true,  italic: false, align: 'left', color: '#111111' },
    skills:      { size: 11, bold: false, italic: false, align: 'left', color: '#2c5f9e' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#111111' },
    jobCompany:  { size: 12, bold: false, italic: false, align: 'left', color: '#2c5f9e' },
    eduDegree:   { size: 13.5, bold: true, italic: false, align: 'left', color: '#111111' },
    eduInst:     { size: 12, bold: false, italic: false, align: 'left', color: '#2c5f9e' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#111111' },
  },
};
