export const CorporateTheme = {
  id: 'corporate',
  name: 'Corporate',
  desc: 'Navy · Formal · Roboto',
  swatches: ['#1e3a5f', '#1e3a5f', '#f4f7fb'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  vars: {
    '--th-font-family': "'Roboto', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#1e3a5f',
    '--th-accent2': '#1e3a5f',
    '--th-page-bg': '#f4f7fb',
    '--th-chip-bg': '#1e3a5f',
    '--th-chip-color': '#ffffff',
    '--th-chip-border': 'none',
    '--th-chip-radius': '3px',
    '--th-sec-rule-w': '1.5px',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '14px',
  },
  typo: {
    headerBg:    { color: '#1e3a5f' },
    sidebarBg:   { color: '#1e3a5f' },
    accentColor: { color: '#1e3a5f' },
    name:        { size: 36, bold: true,  italic: false, align: 'left', color: '#ffffff' },
    title:       { size: 14, bold: false, italic: false, align: 'left', color: '#c0d4f0' },
    sectionTitle:{ size: 13, bold: true,  italic: false, align: 'left', color: '#1e3a5f' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#1e3a5f' },
    jobCompany:  { size: 12, bold: true,  italic: false, align: 'left', color: '#333333' },
    eduDegree:   { size: 13.5, bold: true, italic: false, align: 'left', color: '#1e3a5f' },
    eduInst:     { size: 12, bold: false, italic: false, align: 'left', color: '#333333' },
  },
}
