export const ExecutiveTheme = {
  id: 'executive',
  name: 'Executive',
  desc: 'Dark · Navy · Open Sans',
  swatches: ['#1a2845', '#3070c0', '#f8f9fb'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  vars: {
    '--th-font-family': "'Open Sans', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#3070c0',
    '--th-accent2': '#3070c0',
    '--th-page-bg': '#f8f9fb',
    '--th-chip-bg': 'transparent',
    '--th-chip-color': '#2a3a5c',
    '--th-chip-border': 'none',
    '--th-chip-radius': '0',
    '--th-sec-rule-w': '1px',
    '--th-job-sep-border': '1px solid #e8e8e8',
    '--th-job-sep-pb': '10px',
    '--th-job-sep-mb': '4px',
  },
  typo: {
    headerBg:    { color: '#1a2845' },
    sidebarBg:   { color: '#1a2845' },
    accentColor: { color: '#3070c0' },
    name:        { size: 28, bold: true,  italic: false, align: 'center', color: '#ffffff' },
    title:       { size: 11, bold: false, italic: false, align: 'center', color: '#9ab0cc' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#444444' },
    sectionTitle:{ size: 10.5, bold: true, italic: false, align: 'left', color: '#888888' },
    jobTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    jobCompany:  { size: 11.5, bold: false, italic: false, align: 'left', color: '#3070c0' },
    eduDegree:   { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    eduInst:     { size: 11.5, bold: false, italic: false, align: 'left', color: '#3070c0' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
  },
};
