export const FreshTheme = {
  id: 'fresh',
  name: 'Fresh',
  desc: 'Teal · Light · Lato',
  swatches: ['#ffffff', '#009999', '#ffffff'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  vars: {
    '--th-font-family': "'Lato', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#009999',
    '--th-accent2': '#009999',
    '--th-page-bg': '#ffffff',
    '--th-chip-bg': 'transparent',
    '--th-chip-color': '#009999',
    '--th-chip-border': '1.5px solid #009999',
    '--th-chip-radius': '3px',
    '--th-sec-rule-w': '1px',
    '--th-job-sep-border': '1px dashed #e0e0e0',
    '--th-job-sep-pb': '10px',
    '--th-job-sep-mb': '4px',
  },
  typo: {
    headerBg:    { color: '#ffffff' },
    sidebarBg:   { color: '#1a4a47' },
    accentColor: { color: '#009999' },
    name:        { size: 36, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    title:       { size: 14, bold: false, italic: false, align: 'left', color: '#009999' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#555555' },
    sectionTitle:{ size: 12, bold: true,  italic: false, align: 'left', color: '#777777' },
    skills:      { size: 11, bold: false, italic: false, align: 'left', color: '#009999' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#222222' },
    jobCompany:  { size: 12, bold: false, italic: false, align: 'left', color: '#009999' },
    eduDegree:   { size: 13.5, bold: true, italic: false, align: 'left', color: '#222222' },
    eduInst:     { size: 12, bold: false, italic: false, align: 'left', color: '#009999' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#222222' },
  },
};
