export const LavenderTheme = {
  id: 'lavender',
  name: 'Lavender',
  desc: 'Soft · Blue · Nunito',
  swatches: ['#e8eef8', '#4a6fa5', '#edf1f9'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  defaultGraphic: 'blobs',
  vars: {
    '--th-font-family': "'Nunito', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#4a6fa5',
    '--th-accent2': '#4a6fa5',
    '--th-page-bg': '#edf1f9',
    '--th-chip-bg': 'transparent',
    '--th-chip-color': '#4a6fa5',
    '--th-chip-border': '1.5px solid #4a6fa5',
    '--th-chip-radius': '4px',
    '--th-sec-rule-w': '1.5px',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '14px',
    '--th-blob-display': 'block',
    '--th-blob-color-1': 'rgba(74,111,165,0.12)',
    '--th-blob-color-2': 'rgba(74,111,165,0.08)',
  },
  typo: {
    headerBg:    { color: '#e8eef8' },
    sidebarBg:   { color: '#2a3f5f' },
    accentColor: { color: '#4a6fa5' },
    name:        { size: 36, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    title:       { size: 14, bold: false, italic: false, align: 'left', color: '#4a6fa5' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#555555' },
    sectionTitle:{ size: 13, bold: true,  italic: false, align: 'left', color: '#4a6fa5' },
    skills:      { size: 11, bold: false, italic: false, align: 'left', color: '#4a6fa5' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#4a6fa5' },
    jobCompany:  { size: 12, bold: false, italic: false, align: 'left', color: '#333333' },
    eduDegree:   { size: 13.5, bold: true, italic: false, align: 'left', color: '#4a6fa5' },
    eduInst:     { size: 12, bold: false, italic: false, align: 'left', color: '#333333' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#333333' },
  },
};
