export const MinimalTheme = {
  id: 'minimal',
  name: 'Minimal',
  desc: 'White · Blue · Source Sans',
  swatches: ['#ffffff', '#1d5fa8', '#ffffff'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  sectionStyle: 'overline',
  chipStyle: 'underlined',
  vars: {
    '--th-font-family': "'Source Sans 3', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#1d5fa8',
    '--th-accent2': '#1d5fa8',
    '--th-page-bg': '#ffffff',
    '--th-chip-bg': 'transparent',
    '--th-chip-color': '#1d5fa8',
    '--th-chip-border': 'none',
    '--th-chip-radius': '0',
    '--th-sec-rule-w': '1.5px',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '14px',
  },
  typo: {
    headerBg:    { color: '#ffffff' },
    sidebarBg:   { color: '#1e3a5f' },
    accentColor: { color: '#1d5fa8' },
    name:        { size: 32, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    title:       { size: 13, bold: false, italic: true,  align: 'left', color: '#555555' },
    summary:     { size: 12, bold: false, italic: false, align: 'left', color: '#555555' },
    sectionTitle:{ size: 11.5, bold: true, italic: false, align: 'left', color: '#1d5fa8' },
    jobTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    jobCompany:  { size: 11.5, bold: false, italic: false, align: 'left', color: '#1d5fa8' },
    eduDegree:   { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    eduInst:     { size: 11.5, bold: false, italic: false, align: 'left', color: '#1d5fa8' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
  },
};
