export const SerifTheme = {
  id: 'serif',
  name: 'Serif',
  desc: 'Crimson · Elegant · Classic',
  swatches: ['#2c3e6b', '#2c3e6b', '#fafafa'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,400;0,600;0,700;1,400;1,600&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  vars: {
    '--th-font-family': "'Crimson Pro', Georgia, serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#2c3e6b',
    '--th-accent2': '#2c3e6b',
    '--th-page-bg': '#fafafa',
    '--th-chip-bg': 'transparent',
    '--th-chip-color': '#2c3e6b',
    '--th-chip-border': '1px solid #2c3e6b',
    '--th-chip-radius': '2px',
    '--th-sec-rule-w': '1.5px',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '14px',
  },
  typo: {
    headerBg:    { color: '#2c3e6b' },
    sidebarBg:   { color: '#2c3e6b' },
    accentColor: { color: '#2c3e6b' },
    name:        { size: 40, bold: true,  italic: false, align: 'left', color: '#ffffff' },
    title:       { size: 16, bold: false, italic: true,  align: 'left', color: '#d0d8f0' },
    summary:     { size: 13, bold: false, italic: false, align: 'justify', color: '#444444' },
    sectionTitle:{ size: 13, bold: true,  italic: false, align: 'left', color: '#2c3e6b' },
    jobTitle:    { size: 14, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    jobCompany:  { size: 12, bold: false, italic: true,  align: 'left', color: '#2c3e6b' },
    eduDegree:   { size: 14, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    eduInst:     { size: 12, bold: false, italic: true,  align: 'left', color: '#2c3e6b' },
    achTitle:    { size: 14, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
  },
};
