export const TimelineTheme = {
  id: 'timeline',
  name: 'Timeline',
  desc: 'Navy · Orange · Raleway',
  swatches: ['#1e3a5f', '#e8611a', '#ffffff'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap',
  timelineDecoration: true,
  sectionBadge: false,
  vars: {
    '--th-font-family': "'Raleway', sans-serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#1e3a5f',
    '--th-accent2': '#e8611a',
    '--th-page-bg': '#ffffff',
    '--th-chip-bg': '#1e3a5f',
    '--th-chip-color': '#ffffff',
    '--th-chip-border': 'none',
    '--th-chip-radius': '3px',
    '--th-sec-rule-w': '2.5px',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '10px',
  },
  typo: {
    headerBg:    { color: '#1e3a5f' },
    sidebarBg:   { color: '#1e3a5f' },
    accentColor: { color: '#1e3a5f' },
    name:        { size: 36, bold: true,  italic: false, align: 'left', color: '#ffffff' },
    title:       { size: 13, bold: false, italic: false, align: 'left', color: '#b0c4de' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#555555' },
    sectionTitle:{ size: 12, bold: true,  italic: false, align: 'left', color: '#1e3a5f' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#1e3a5f' },
    jobCompany:  { size: 12, bold: true,  italic: false, align: 'left', color: '#e8611a' },
    eduDegree:   { size: 13, bold: true,  italic: false, align: 'left', color: '#1e3a5f' },
    eduInst:     { size: 12, bold: false, italic: false, align: 'left', color: '#e8611a' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1e3a5f' },
  },
};
