export const VibrantTheme = {
  id: 'vibrant',
  name: 'Vibrant',
  desc: 'Green · Badges · Poppins',
  swatches: ['#ffffff', '#2a9d5c', '#f4fbf7'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;1,400&display=swap',
  timelineDecoration: false,
  sectionBadge: true,
  titlePill: true,
  defaultGraphic: 'blobs',
  vars: {
    '--th-font-family': "'Poppins', sans-serif",
    '--th-photo-radius': '14px',
    '--th-accent': '#2a9d5c',
    '--th-accent2': '#2a9d5c',
    '--th-badge-color': '#2a9d5c',
    '--th-title-bg': '#2a9d5c',
    '--th-page-bg': '#f4fbf7',
    '--th-chip-bg': '#2a9d5c',
    '--th-chip-color': '#ffffff',
    '--th-chip-border': 'none',
    '--th-chip-radius': '20px',
    '--th-sec-rule-w': '0',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '16px',
    '--th-blob-display': 'block',
    '--th-blob-color-1': 'rgba(42,157,92,0.10)',
    '--th-blob-color-2': 'rgba(42,157,92,0.07)',
  },
  typo: {
    headerBg:    { color: '#ffffff' },
    sidebarBg:   { color: '#1a4a2e' },
    accentColor: { color: '#2a9d5c' },
    name:        { size: 34, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    title:       { size: 13, bold: true,  italic: false, align: 'left', color: '#2a9d5c' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#444444' },
    sectionTitle:{ size: 12, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    jobTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    jobCompany:  { size: 11.5, bold: true, italic: false, align: 'left', color: '#2a9d5c' },
    eduDegree:   { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
    eduInst:     { size: 11.5, bold: true, italic: false, align: 'left', color: '#2a9d5c' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#1a1a1a' },
  },
};
