export const WarmTheme = {
  id: 'warm',
  name: 'Warm',
  desc: 'Terracotta · Earthy · Lora',
  swatches: ['#3d1e0a', '#c8602a', '#fdf8f4'],
  googleFontUrl: 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&display=swap',
  timelineDecoration: false,
  sectionBadge: false,
  sectionStyle: 'left-accent',
  vars: {
    '--th-font-family': "'Lora', Georgia, serif",
    '--th-photo-radius': '50%',
    '--th-accent': '#c8602a',
    '--th-accent2': '#c8602a',
    '--th-page-bg': '#fdf8f4',
    '--th-chip-bg': 'rgba(200,96,42,0.09)',
    '--th-chip-color': '#7a3010',
    '--th-chip-border': '1.5px solid #c8602a',
    '--th-chip-radius': '3px',
    '--th-sec-rule-w': '0',
    '--th-job-sep-border': 'none',
    '--th-job-sep-pb': '0',
    '--th-job-sep-mb': '14px',
  },
  typo: {
    headerBg:    { color: '#3d1e0a' },
    sidebarBg:   { color: '#3d1e0a' },
    accentColor: { color: '#c8602a' },
    name:        { size: 36, bold: true,  italic: false, align: 'left', color: '#ffffff' },
    title:       { size: 14, bold: false, italic: true,  align: 'left', color: '#f0b896' },
    summary:     { size: 12, bold: false, italic: false, align: 'justify', color: '#4a3328' },
    sectionTitle:{ size: 12, bold: true,  italic: false, align: 'left', color: '#c8602a' },
    jobTitle:    { size: 13.5, bold: true, italic: false, align: 'left', color: '#2a1408' },
    jobCompany:  { size: 12, bold: false, italic: true,  align: 'left', color: '#c8602a' },
    jobPeriod:   { size: 11, bold: false, italic: false, align: 'left', color: '#8b6050' },
    eduDegree:   { size: 13.5, bold: true, italic: false, align: 'left', color: '#2a1408' },
    eduInst:     { size: 12, bold: false, italic: true,  align: 'left', color: '#c8602a' },
    achTitle:    { size: 13, bold: true,  italic: false, align: 'left', color: '#2a1408' },
  },
};
